# Discrete choice modelling

## The conditional logit with ModeCanada dataset

In [ ]:
from choice_learn.datasets import load_modecanada
from choice_learn.data import ChoiceDataset
transport_df = load_modecanada(as_frame=True)
print(f"Dataset shape: {transport_df.shape}")
display(transport_df.head(8))

Dataset shape: (15520, 11)

   case    alt  choice  dist   cost  ivt  ovt  freq  income  urban  noalt
0     1  train       0    83  28.25   50   66     4    45.0      0      2
1     1    car       1    83  15.77   61    0     0    45.0      0      2
2     2  train       0    83  28.25   50   66     4    25.0      0      2
3     2    car       1    83  15.77   61    0     0    25.0      0      2
4     3  train       0    83  28.25   50   66     4    70.0      0      2
5     3    car       1    83  15.77   61    0     0    70.0      0      2
6     4  train       0    83  28.25   50   66     4    70.0      0      2
7     4    car       1    83  15.77   61    0     0    70.0      0      2

### Exploring case 1

In [5]:
transport_df.loc[transport_df["case"] == 1,:]

   case    alt  choice  dist   cost  ivt  ovt  freq  income  urban  noalt
0     1  train       0    83  28.25   50   66     4    45.0      0      2
1     1    car       1    83  15.77   61    0     0    45.0      0      2

For case 1 there were two alternative and the car was choen over the train

### Coverting to ChoiceDataset